name: build-test
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    install:
      - sudo apt update -qq
      - sudo apt install -qq libboost-all-dev
    steps:
      - uses: actions/checkout@v2
      - run: autoreconf -v -f -i
      - run: ./configure
      - run: make
      - run: make check
      - run: make distcheck
