name: build-test
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: autoreconf -v -f -i
    - run: ./configure
    - run: make
    - run: make check
    - run: make distcheck
